# Generated by Django 5.0.2 on 2024-02-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.ImageField(default='default', upload_to='uploads/songs/'),
        ),
    ]
